import React, { useState, useEffect } from 'react';
import { FileText, Download, Filter, CheckCircle2 } from 'lucide-react';
import DataTable from '../../components/tables/DataTable';
import Badge from '../../components/common/Badge';
import Button from '../../components/common/Button';
import { useToast } from '../../context/ToastContext';
import { reportService } from '../../services';

export default function GlobalReportsPage() {
  const { addToast } = useToast();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const data = await reportService.getSuperAdminReports();
      setReports(data || []);
    } catch (err) {
      addToast('Failed to load reports', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerateReport = async () => {
    try {
      addToast('Generating fresh system-wide report...', 'info');
      const newReport = await reportService.generateReport('super_admin', 'Consolidated System Audit');
      setReports((prev) => [newReport, ...prev]);
      addToast('Report generated successfully', 'success');
    } catch (err) {
      addToast('Failed to generate report', 'error');
    }
  };

  const columns = [
    {
      key: 'name',
      label: 'Report Title',
      render: (row) => (
        <div>
          <div style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{row.name}</div>
          <div style={{ fontSize: '11px', color: 'var(--text-tertiary)' }}>ID: {row.id} • Format: {row.format} ({row.size})</div>
        </div>
      ),
    },
    {
      key: 'generatedDate',
      label: 'Generated On',
      render: (row) => <span style={{ fontSize: '12.5px' }}>{row.generatedDate}</span>,
    },
    {
      key: 'generatedBy',
      label: 'Generated By',
      render: (row) => <span style={{ fontSize: '12.5px', color: 'var(--text-secondary)' }}>{row.generatedBy}</span>,
    },
    {
      key: 'status',
      label: 'Status',
      render: (row) => <Badge variant="success">{row.status}</Badge>,
    },
    {
      key: 'actions',
      label: 'Action',
      sortable: false,
      render: (row) => (
        <Button
          variant="secondary"
          size="sm"
          icon={Download}
          onClick={() => addToast(`Downloading ${row.name}...`, 'info')}
        >
          Download
        </Button>
      ),
    },
  ];

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">Global Audit & Compliance Reports</h1>
          <p className="page-subtitle">Centralized regulatory downloads, financial consolidation, and system logs</p>
        </div>
        <Button variant="primary" icon={FileText} onClick={handleGenerateReport}>
          Generate Custom Report
        </Button>
      </div>

      <DataTable
        columns={columns}
        data={reports}
        title="Archived System Reports"
        subtitle="Download official snapshots for audit, NIRF, and governance"
        searchPlaceholder="Search reports..."
        searchKeys={['name', 'id', 'generatedBy']}
        loading={loading}
      />
    </div>
  );
}
